import { expect, test } from '@playwright/test'

for (const kind of ['http', 'agui']) test('A2UI v1 ' + kind + ': live bindings, remote functions, validation, submit, deletion', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: /^Connections/ }).click()
  const drawer = page.getByRole('dialog', { name: 'Connections' })
  await drawer.getByLabel('Connection type').selectOption(kind)
  await drawer.getByLabel('Name', { exact: true }).fill('A2UI ' + kind)
  await drawer.getByLabel('Endpoint URL', { exact: true }).fill('http://127.0.0.1:9101/a2ui/' + (kind === 'http' ? 'http' : 'ag-ui'))
  if (kind === 'http') await drawer.getByLabel('Request mapping (JSON)').fill('{"prompt":"$prompt","messages":"$a2uiMessages","metadata":"$metadata"}')
  await drawer.getByRole('button', { name: 'Add connection' }).click()
  await drawer.locator('article').filter({ hasText: 'A2UI ' + kind }).getByRole('button', { name: 'Use', exact: true }).click()
  await page.getByPlaceholder('Message A2UI ' + kind + '…').fill('Show a form')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  const canvas = page.locator('.canvas-panel')
  await expect(canvas.getByText('Dynamic row two')).toBeVisible()
  await expect(canvas.getByRole('button', { name: 'Submit form' })).toBeDisabled()
  await expect(canvas.getByText('Hello visitor')).toBeVisible()
  await canvas.getByLabel('Your name').fill('Grace')
  await expect(canvas.getByText('Hello Grace')).toBeVisible()
  await expect(canvas.getByRole('button', { name: 'Submit form' })).toBeEnabled()
  await canvas.getByRole('button', { name: 'Submit form' }).click()
  await expect(canvas.getByText('Saved Grace')).toBeVisible()
  await expect(page.locator('.messages')).not.toContainText('UI action:')
  await page.screenshot({ path: test.info().outputPath('a2ui-v1-' + kind + '.png'), fullPage: true })
  await canvas.getByRole('button', { name: 'Delete surface' }).click()
  await expect(canvas.locator('[data-surface-id="fixture-form"]')).toHaveCount(0)
  expect(errors).toEqual([])
})
